linters:
  presets:
    - bugs
    - comment
    - complexity
    - error
    - format
    - import
    - metalinter
    - module
    - performance
    - sql
    - style
    - test
    - unused
  enable:
    - govet
    - exportloopref
    - revive
  disable:
    - wrapcheck
    - ireturn
    - varnamelen
    - exhaustivestruct
    - gofumpt
    - goimports
    - maligned
    - scopelint
    - golint
    - interfacer
    - godot