// Code generated by mockery v2.10.0. DO NOT EDIT.

package mocks

import (
	gin "github.com/gin-gonic/gin"
	mock "github.com/stretchr/testify/mock"

	routes "jimmy_tech_crud_gin/routes"
)

// Route is an autogenerated mock type for the Route type
type Route struct {
	mock.Mock
}

// GetHandler provides a mock function with given fields:
func (_m *Route) GetHandler() routes.RouteHandlerFunc {
	ret := _m.Called()

	var r0 routes.RouteHandlerFunc
	if rf, ok := ret.Get(0).(func() routes.RouteHandlerFunc); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(routes.RouteHandlerFunc)
		}
	}

	return r0
}

// GetMethod provides a mock function with given fields:
func (_m *Route) GetMethod() string {
	ret := _m.Called()

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// GetMiddleware provides a mock function with given fields:
func (_m *Route) GetMiddleware() []gin.HandlerFunc {
	ret := _m.Called()

	var r0 []gin.HandlerFunc
	if rf, ok := ret.Get(0).(func() []gin.HandlerFunc); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]gin.HandlerFunc)
		}
	}

	return r0
}

// GetPath provides a mock function with given fields:
func (_m *Route) GetPath() string {
	ret := _m.Called()

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}
